//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RooyaDev {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RooyaDev.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Job.
        /// </summary>
        public static string AboutJob {
            get {
                return ResourceManager.GetString("AboutJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Project.
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string AboutService {
            get {
                return ResourceManager.GetString("AboutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddComments To Admin.
        /// </summary>
        public static string AddCommentsToAdmin {
            get {
                return ResourceManager.GetString("AddCommentsToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply In This Job.
        /// </summary>
        public static string ApplyInthisjob {
            get {
                return ResourceManager.GetString("ApplyInthisjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloger.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cairo.
        /// </summary>
        public static string Cairo {
            get {
                return ResourceManager.GetString("Cairo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Carrers {
            get {
                return ResourceManager.GetString("Carrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeadLine.
        /// </summary>
        public static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Valid DeadLine.
        /// </summary>
        public static string DeadLineError {
            get {
                return ResourceManager.GetString("DeadLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DesignDesc {
            get {
                return ResourceManager.GetString("DesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Games.
        /// </summary>
        public static string DesignGames {
            get {
                return ResourceManager.GetString("DesignGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To produce games with interesting content, good and gradual in the levels and supported by incentives and tasks. Cut any road to boredom and increase the attract attention of the user as it provides the game industry services to others by converting ideas to games with a real pressure and high quality to achieve the customer all that aims to obtain the production of a game in a different form and style different from the one on the scene.
        /// </summary>
        public static string DesignGamesDesc {
            get {
                return ResourceManager.GetString("DesignGamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string E_Mail {
            get {
                return ResourceManager.GetString("E_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Is Used !.
        /// </summary>
        public static string EmailUsed {
            get {
                return ResourceManager.GetString("EmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter PDF File.
        /// </summary>
        public static string enterpdffile {
            get {
                return ResourceManager.GetString("enterpdffile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Development was established in 2013 to meet the growing needs in the field of technology in Saudi Arabia, Egypt and the Arab world by providing high quality and reliable services in various branches of information technology.
        ///The idea of ​​the company has emerged as a result of our continuous follow-up of the Saudi, Egyptian and Arab markets in general, and its continuous and simultaneous development with our technological and information revolution, Modern - if not all - what modern institutions ne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HistoryDesc {
            get {
                return ResourceManager.GetString("HistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through our years of experience, we have been able to offer a wide range of products, solutions and services to Nestor, thus creating successive successes based on our policy to create and create quality services that meet the aspirations of our customers from all sectors. Our study of the booming local market, which lasted nearly two years before the launch of the company&apos;s activities, contributed directly and effectively to achieving our main objectives by creating a new Saudi international company that c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeDesc {
            get {
                return ResourceManager.GetString("HomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision International is a leading global provider of web hosting, web design, smart device applications, e-marketing, technical production, and many technical services that have helped the business community to complete their business as quickly as possible. Special over the past five years professionally and technically helped in its success and meet its requirements..
        /// </summary>
        public static string HomeDescFotter {
            get {
                return ResourceManager.GetString("HomeDescFotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Services.
        /// </summary>
        public static string HomeHead {
            get {
                return ResourceManager.GetString("HomeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email &amp; Password.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Applied to Job Successfuly.
        /// </summary>
        public static string JobDone {
            get {
                return ResourceManager.GetString("JobDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KSA.
        /// </summary>
        public static string KSA {
            get {
                return ResourceManager.GetString("KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have designed hundreds of professional mobile applications in more than one language and for our customers spread across the world. We have contributed to many major projects based on mobile applications and systems. We seek to change the reality of mobile applications in the Arab world and make them really easy and available to all..
        /// </summary>
        public static string MobileDevDesc {
            get {
                return ResourceManager.GetString("MobileDevDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Development.
        /// </summary>
        public static string MobileDevelopment {
            get {
                return ResourceManager.GetString("MobileDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Carrers.
        /// </summary>
        public static string NoCarrers {
            get {
                return ResourceManager.GetString("NoCarrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Custom Project.
        /// </summary>
        public static string OrderCustomProject {
            get {
                return ResourceManager.GetString("OrderCustomProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Order A Project Successfuly .. Please Wait our Answer.
        /// </summary>
        public static string OrderDone {
            get {
                return ResourceManager.GetString("OrderDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Your Price.
        /// </summary>
        public static string OrderYourPrice {
            get {
                return ResourceManager.GetString("OrderYourPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our ability to execute beyond imagination and remain required of the client is the basis for us to imagine, creativity and implementation. We are committed to all that achieves its objectives in its desired work. Just simple steps, your works will be ready to use and you are in your place with one click. These are some of the reasons that make us your first choice always.
        /// </summary>
        public static string PricingDesc {
            get {
                return ResourceManager.GetString("PricingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string ProjectDesc {
            get {
                return ResourceManager.GetString("ProjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooaya Development.
        /// </summary>
        public static string RooayaDevelopment {
            get {
                return ResourceManager.GetString("RooayaDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Admin.
        /// </summary>
        public static string Sendtoadmin {
            get {
                return ResourceManager.GetString("Sendtoadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out .
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Work.
        /// </summary>
        public static string startyourwork {
            get {
                return ResourceManager.GetString("startyourwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Our Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Production.
        /// </summary>
        public static string TechnicalProduction {
            get {
                return ResourceManager.GetString("TechnicalProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company&apos;s vision includes the production of television and radio works and the implementation of commercial and documentary films for the sectors of the state and private sector institutions. Our services include all stages of production and requirements such as script writing, photography, editing, graphics, audio and visual effects..
        /// </summary>
        public static string TechnicalProductionDes {
            get {
                return ResourceManager.GetString("TechnicalProductionDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Project Is Finished.
        /// </summary>
        public static string ThisProjectIsFinished {
            get {
                return ResourceManager.GetString("ThisProjectIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Project Is Out Of Date.
        /// </summary>
        public static string ThisProjectIsOutOfDate {
            get {
                return ResourceManager.GetString("ThisProjectIsOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training courses and technical consulting.
        /// </summary>
        public static string Trainig {
            get {
                return ResourceManager.GetString("Trainig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer you a full range of solutions, including IT consulting, network consulting and emergency consulting, which may take place at any time, with many services covering many important aspects..
        /// </summary>
        public static string TrainigDesc {
            get {
                return ResourceManager.GetString("TrainigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Work.
        /// </summary>
        public static string UnderWork {
            get {
                return ResourceManager.GetString("UnderWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload A PDF File.
        /// </summary>
        public static string Uploadapdffile {
            get {
                return ResourceManager.GetString("Uploadapdffile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload CV (PDF).
        /// </summary>
        public static string UploadCV {
            get {
                return ResourceManager.GetString("UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various design services, suited to all needs
        ///We are pleased to see the development of your site in a professional manner in accordance with the highest international standards and in a structured manner of content prefer to choose one of the special packages and let us start your site for the sky of creativity..
        /// </summary>
        public static string WebDevDesc {
            get {
                return ResourceManager.GetString("WebDevDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Development.
        /// </summary>
        public static string WebDevelopment {
            get {
                return ResourceManager.GetString("WebDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Whow {
            get {
                return ResourceManager.GetString("Whow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaya Information Technology and Technical Production Est.
        ///Is an official Egyptian institution (registered by the Saudi Egyptian regulatory bodies) specialized in the design and development of systems, websites, applications and smart devices.
        /// </summary>
        public static string WhowDesc {
            get {
                return ResourceManager.GetString("WhowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vision of evolution combines confidence, high performance, ease of use and technical support that aim to meet your desires as quickly as possible. We also provide you with all the technical systems you need to facilitate all your work, just by simple steps and one click and you are in your site.
        ///Trust and safety
        ///Our work is based on trust between you and us. Unless we are legally bound to disclose, we are committed to protecting and maintaining the confidentiality of any information about you. We will [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhyDesc {
            get {
                return ResourceManager.GetString("WhyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Rooya Development.
        /// </summary>
        public static string WhyRooya {
            get {
                return ResourceManager.GetString("WhyRooya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Order This Price.
        /// </summary>
        public static string YouOrderThisPrice {
            get {
                return ResourceManager.GetString("YouOrderThisPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Gateway to The World of Technology.
        /// </summary>
        public static string YourGateway {
            get {
                return ResourceManager.GetString("YourGateway", resourceCulture);
            }
        }
    }
}
